---
name: cffconvert

on:
  push:
    paths:
      - CITATION.cff

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate
