---

name: "Lint"
run-name: "Linters started by @${{ github.actor }}"
permissions: read-all

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  citations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: citation-file
        run: echo "exists=$(test -f CITATION.cff && echo 'true' || echo 'false')" | tee -a "${GITHUB_OUTPUT}"

      - if: steps.citation-file.outputs.exists
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate

  markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: "**/*.md"
          dot: true

  yaml:
    name: Lint and Reformat Yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTO_YAML_FMT_DOTGITHUB }}

      - run: go install "github.com/google/yamlfmt/cmd/yamlfmt@latest"
      - run: ~/go/bin/yamlfmt .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            Reformat yaml files

            This is an automated commit.

      - uses: ibiqlik/action-yamllint@v3
        with:
          strict: true
          format: parsable
          config_data: |
            extends: default
            rules:
              line-length: disable
              truthy:
                check-keys: false
                allowed-values:
                  - "true"
                  - "false"

  editorconfig:
    name: Check Against EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@v1.0.0

  actionlint:
    name: Lint Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: norwd/actionlint@main
